config/routes.rb
Rails.application.routes.draw do

  devise_for :recruiters
  devise_for :job_seekers
  resources :jobs
  match "apply_job", to: 'jobs#apply', via: :patch
  namespace :dashboard do
    
    authenticated :recruiter do
      get 'profiles/show'
      get 'profiles/edit'
      patch 'profiles/update'
    end

    authenticated :job_seeker do
      get 'profiles/show'
      get 'profiles/edit'
      patch 'profiles/update'
    end

    root to: "dashboard#index"
    

  end
  get 'welcomes/index'
  get 'welcomes/register' => 'welcomes#register'
  root to: 'welcomes#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/job.rb
class Dashboard::Job < ApplicationRecord
	belongs_to :recruiter
	has_many :job_applications 
	has_many :job_seekers, through: :job_applications
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :recruiter
	has_many :job_applications, dependent: :destroy
	has_many :job_seekers, through: :job_applications

	searchkick text_middle: [:title]
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job
  belongs_to :job_seeker
end

app/models/job_seeker.rb
class JobSeeker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :job_applications
	has_many :jobs, through: :job_applications

	after_create :send_email
	def send_email
		UserMailer.jobseeker_email(self).deliver_now		
	end
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :jobs, dependent: :destroy

  after_create :send_email
  def send_email
  	UserMailer.recruiter_email(self).deliver_now		
  end
  searchkick text_middle: [:cname, :clocation]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	devise_group :user, contains: [:recruiter,:job_seeker]
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  def index
    @job_locations = Job.pluck(:job_location).uniq
    @job = Job.new
		if params[:search] or params[:salary] or params[:experience] or params[:location]
			@jobs = Job.search(body: search_query.to_json).results
      @recruiter_jobs = Job.where(recruiter_id: current_user.id).where("title LIKE ?","%#{params[:search]}%")
    else
      @applied_jobs = Job.joins(:job_seekers).map{|job| job if job.job_seekers.ids.include?(current_user.id)}.compact.uniq
      @all_jobs = Job.all.to_a - @applied_jobs
      @recruiter_jobs = Job.where(recruiter_id: current_user.id)
		end
  end

  private

  def search_query
    {
      query: {
        bool: {
          must: must_query,
          filter: filters
        }
      },
      size: 10000,
    }
  end

  def filters
    filters = []
    filters << { range: { salary: {lte: params[:salary]} } } if params[:salary].present?
    filters << { range: { experience: {lte: params[:experience]} } } if params[:experience].present?
    filters << { term: { job_location: params[:location] } } if params[:location].present?
    filters
  end

  def must_query
    must = []
    if params[:search].present?
      must << multi_match_query
    else
      must = [
        match_all: {}
      ]
    end
    must
  end

  def multi_match_query
    {
     wildcard: {
     	title: {
       value: "*#{params[:search]}*"
     		}
   		}
    }
  end
end

app/controllers/dashboard/profiles_controller.rb
class Dashboard::ProfilesController < ApplicationController
  def show
	end

	def edit

		@user=current_user	
	end

	def update
		@user = current_user
		respond_to do |format|
			if @user.update(user_params)
				format.html {redirect_to dashboard_profiles_show_url, notice: 'your profile is updated successfully.' }
			else
				format.html { render :edit }
	    end 
		end
end

private

	def user_params
		if current_user.instance_of?JobSeeker		
			params.require(:job_seeker).permit(:name, :qualification, :skills, :dob, :experience)
		else
			params.require(:recruiter).permit(:cname, :description, :clocation, :csize)
		end
  end	
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :check_recruiter, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  def apply
    user = current_job_seeker
    job = Job.find(params[:format])
    job.job_seekers << current_job_seeker
    UserMailer.recruiter_apply(job,user).deliver_now
    UserMailer.jobseeker_apply(job,user).deliver_now
    redirect_to '/', notice: 'Applied successfully!'
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
 
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to dashboard_root_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to dashboard_root_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_root_path, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #checks wheather the current user is a recruiter
    def check_recruiter
      unless current_recruiter
        redirect_to dashboard_root_path, notice: 'You are not authorized'
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :salary, :experience, :job_location, :recruiter_id)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  	if current_user
  		redirect_to :controller => 'dashboard/dashboard', :action => 'index' 
  	end
  end

  def register
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/dashboard/profiles_helper.rb
module Dashboard::ProfilesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/dashboard/dashboard/_jobseeker.html.erb
<form class="form-background margin2">
	<div class="row mt-1">
	<input type="text" class="form-control form-search col-md-4 mr-1 ml-4" placeholder="Search"  name= "search" >


	<div class="btn-group col-md-2 mr-1 " >
		<select class="btn button-custom btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="salary">
			<div class="dropdown-menu">
				<option value="none" selected disabled hidden class="dropdown-item"> 
				Salary</option>
				<% (1..10).each do |salary| %>
					<option value="<%= salary*200000 %>" class="dropdown-item"> <%= salary*2 %> Lakhs </option>
				<% end %>
			</div>
		</select>
	</div>

	<div class="btn-group col-md-2 mr-1" >
		<select class="btn button-custom btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="experience">
			<div class="dropdown-menu" >
				<option value="none" selected disabled hidden class="dropdown-item"> 
				Experience </option>
				<% (1..5).each do |experience| %>
					<option value="<%= experience*2 %>" class="dropdown-item"> <%= experience*2 %> Years </option>
				<% end %>              	
			</div>
		</select>
	</div> 

	<div class="btn-group col-md-2 mr-2" >
		<select class="btn button-custom btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="location"> 
			<div class="dropdown-menu" >
				<option value="none" selected disabled hidden class="dropdown-item"> 
				Location </option>     
				<%= options_for_select(@job_locations) %>         	
			</div>
		</select>
	</div> 
		<button type="submit" class="btn btn-primary col-md-1"> Search </button>
	</div>
</form>

<% if params[:search] %>
	<div class="row">
		<% @jobs.each do |job| %>
			<div class="col-sm-12 mb-3 ">
				<div class="card shadow p-3 mb-5 bg-white rounded">
					<div class="card-body">
						<h4 class="card-title"><%= job.title %></h4>
						<p class="card-text"><%= job.description %></p>
						<button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#collapseExample<%= job.id %>" aria-expanded="false" aria-controls="collapseExample<%= job.id %>">Show more</button>
						<br/>
						<div class="collapse" id="collapseExample<%= job.id %>">
							<br/>
							<p>
								<strong>Salary:</strong>
								<%= job.salary %>
							</p>

							<p>
								<strong>Experience:</strong>
								<%= job.experience %>
							</p>

							<p>
								<strong>Job location:</strong>
								<%= job.job_location %>
							</p>

							<p>
								<strong>Company name:</strong>
								<%= job.recruiter.cname %>
							</p>

							<p>
								<strong>Description:</strong>
								<%= job.recruiter.description %>
							</p>

							<p>
								<strong>Company location:</strong>
								<%= job.recruiter.clocation %>
							</p>

							<p>
								<strong>Company size:</strong>
								<%= job.recruiter.csize %>
							</p>
							<% if JobApplication.where(job_seeker_id: current_user.id, job_id: job.id).present? %>
								<strong> Already Applied</strong>
							<% else %>
								<%= link_to "Apply", apply_job_path(job), method: :patch, class: "btn btn-primary float-right" %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% else %>
	<ul class="nav nav-tabs mt-3" id="myTab" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">All Jobs</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Applied Jobs</a>
		</li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tabss">
			<div class="row">
				<% @all_jobs.each do |job| %>
				<div class="col-sm-12 mb-3">
					<div class="card shadow p-3 mb-5 bg-white rounded">
						<div class="card-body">
							<h4 class="card-title"><%= job.title %></h4>
							<p class="card-text"><%= job.description %></p>
							<button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#collapseExample<%= job.id %>" aria-expanded="false" aria-controls="collapseExample<%= job.id %>">Show more</button>
							<br/>
							<div class="collapse" id="collapseExample<%= job.id %>">
								<br/>
								<p>
									<strong>Salary:</strong>
									<%= job.salary %>
								</p>

								<p>
									<strong>Experience:</strong>
									<%= job.experience %>
								</p>

								<p>
									<strong>Job location:</strong>
									<%= job.job_location %>
								</p>

								<p>
									<strong>Company name:</strong>
									<%= job.recruiter.cname %>
								</p>

								<p>
									<strong>Description:</strong>
									<%= job.recruiter.description %>
								</p>

								<p>
									<strong>Company location:</strong>
									<%= job.recruiter.clocation %>
								</p>

								<p>
									<strong>Company size:</strong>
									<%= job.recruiter.csize %>
								</p>
								<%= link_to "Apply", apply_job_path(job), method: :patch, class: "btn btn-primary float-right" %>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>

		<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
			<% if @applied_jobs.present? %>
				<% @applied_jobs.each do |applied_job| %>
					<div class="col-sm-12 mb-3 ">
						<div class="card shadow p-3 mb-5 bg-white rounded">
							<div class="card-body">
								<h4 class="card-title"><%= applied_job.title %></h4>
								<p class="card-text"><%= applied_job.description %></p>
								<button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#collapseExample<%= applied_job.id %>" aria-expanded="false" aria-controls="collapseExample<%= applied_job.id %>">Show more</button>
								<br/>
								<div class="collapse" id="collapseExample<%= applied_job.id %>">
									<br/>
									<p>
										<strong>Salary:</strong>
										<%= applied_job.salary %>
									</p>
									<p>
										<strong>Experience:</strong>
										<%= applied_job.experience %>
									</p>

									<p>
										<strong>Job location:</strong>
										<%= applied_job.job_location %>
									</p>

									<p>
										<strong>Company name:</strong>
										<%= applied_job.recruiter.cname %>
									</p>

									<p>
										<strong>Description:</strong>
										<%= applied_job.recruiter.description %>
									</p>

									<p>
										<strong>Company location:</strong>
										<%= applied_job.recruiter.clocation %>
									</p>

									<p>
										<strong>Company size:</strong>
										<%= applied_job.recruiter.csize %>
									</p>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/dashboard/dashboard/_recruiter.html.erb
<form class="search-form margin5" action="/dashboard" >
	<input type="text" class="form-control" name="search" placeholder="Search" required>
	<button type="submit" style="margin-top: -12px;"><i class="fa fa-search searchIcon"></i></button>
</form>

<div class="inline">
	<div class="font-weight-bold text-capitalize mb-3 mt-3" style="font-size: 20px;">Jobs Posted</div>
	<button type="button" class="btn btn-primary" style="height: 40px; margin-top: 10px;" data-toggle="modal" data-target="#newSite">New Job</button>
	<div class="modal fade" id="newSite" role="dialog" >
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title">Add New Job</h1>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body pr-33">
					<%= render 'form_job', job: @job %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
</div>

<% @recruiter_jobs.each do |job| %>
	<div class="row justify-content-center align-items-center">
		<div class="col-sm-10 mb-3 ">
			<div class="card shadow p-3 mb-5 bg-white rounded">
				<div class="card-body">
					<h4 class="card-title"><%= job.title%></h4>
					<p class="card-text"><%= job.description %></p>
					<button onclick="changeText()" class="btn btn-primary" id="toggle<%= job.id %>" type="button" data-toggle="collapse" data-target="#collapseExample<%= job.id %>" aria-expanded="false" aria-controls="collapseExample<%= job.id %>">Show More</button>
					<div class="collapse" id="collapseExample<%= job.id %>">
						<p>
							<strong>Salary:</strong>
							<%= job.salary %>
						</p>

						<p>
							<strong>Experience:</strong>
							<%= job.experience %>
						</p>

						<p>
							<strong>Job location:</strong>
							<%= job.job_location %>
						</p>

						<p>
							<div class="font-weight-bold text-capitalize mb-3 mt-3" style="font-size: 20px;">Developer Name:</div>
							<% job.job_seekers.each do |jobseeker|%>
								<div class="inline">
									<a data-toggle="modal" data-target="#developer" href="#"><%= jobseeker.name%></a>
									<div class="modal fade" id="developer" role="dialog" >
										<div class="modal-dialog modal-lg">
											<div class="modal-content">
												<div class="modal-header">
													<h1 class="modal-title"><%= jobseeker.name%></h1>
													<button type="button" class="close" data-dismiss="modal">&times;</button>
												</div>
												<div class="modal-body pr-33">
													<div class="form-group">
														<%=  :Email%>
														<%= jobseeker.email %>
													</div>
													<div class="form-group">
														<%=  :Qualification %>
														<%= jobseeker.qualification %>
													</div>
													<div class="form-group">
														<%=  :Skills %>
														<%= jobseeker.skills %>
													</div>
													<div class="form-group">
														<%=  :Experience %>
														<%= jobseeker.experience %>
													</div>
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							<% end %>
						</p>
						<%= link_to "Edit", edit_job_path(job), :type => "button", :class => "btn btn-primary", "data-toggle" => "modal", "data-target" => "#jobEdit#{job.id}" %>
						<%= link_to 'Delete', job, method: :delete, :type => "button", :class => "btn btn-primary", data: { confirm: 'Are you sure?' } %>
						<div class="modal fade" id="jobEdit<%= job.id %>" role="dialog" >
							<div class="modal-dialog modal-lg">
								<div class="modal-content">
									<div class="modal-header">
										<h1 class="modal-title">Add New Job</h1>
										<button type="button" class="close" data-dismiss="modal">&times;</button>
									</div>
									<div class="modal-body pr-33">
										<%= render 'form_job', job: job %>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
									</div>
								</div>
							</div>
						</div>
					<script>
					  const toggle = () => {
					    var dots = document.getElementById("dots");
					    var moreText = document.getElementById("more");
					    var btnText = document.getElementById('<%= job.id %>');

					    if (dots.style.display === "none") {
					      dots.style.display = "inline";
					      btnText.innerHTML = "Show more";
					      moreText.style.display = "none";
					    } else {
					      dots.style.display = "none";
					      btnText.innerHTML = "Show less";
					      moreText.style.display = "inline";
					    }
					  }
					</script>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		function changeText(){
			if (document.getElementById("toggle<%= job.id %>").innerHTML == "Show More") {
				document.getElementById("toggle<%= job.id %>").innerHTML = "Show Less";
			}else {
				document.getElementById("toggle<%= job.id %>").innerHTML = "Show More";
			}
		}
	</script>
<% end %>

app/views/dashboard/profiles/edit.html.erb
<div class="d-flex flex-column justify-content-center align-items-center  flex-1" style="flex: 1">
<h1>Edit your profile</h1>

<% if current_user.instance_of? JobSeeker %>
	
	<%= form_with model: @user, url: {controller: "profiles", action: "update"} do |form|%>


			<div class="form-group">
				<%= form.label :name %>
				<%= form.text_field :name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :qualification %>
				<%= form.text_field :qualification, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :skills %>
				<%= form.text_area :skills, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :dob %>
				<%= form.text_field :dob, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :experience %>
				<%= form.text_field :experience, class: "form-control" %>
			</div>

			<div class="actions">
				<%= form.submit %>
			</div>
	<% end %>

<% elsif current_user.instance_of? Recruiter %>
		

			<%= form_with model: @user, url: {controller: "profiles", action: "update"} do |form|%>

				<div class="form-group">
					<%= form.label :c_name %>
					<%= form.text_field :cname , class: "form-control"%>
				</div>

				<div class="form-group">
					<%= form.label :description %>
					<%= form.text_area :description, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= form.label :c_location %>
					<%= form.text_field :clocation, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= form.label :c_size%>
					<%= form.text_field :csize, class: "form-control" %>
				</div>	
		
				<div class="actions">
					<%= form.submit %>
				</div>
			<% end %>
<% end %>

<%= link_to 'Show', dashboard_profiles_show_path %>



</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Experience</th>
      <th>Job location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.experience %></td>
        <td><%= job.job_location %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @job.experience %>
</p>

<p>
  <strong>Job location:</strong>
  <%= @job.job_location %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheRubyRails</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="/assets/favicon.png" rel="icon">
    <link href="/assets/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Main Stylesheet File -->


    <link href="/assets/style.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <!--==========================
  Header
  ============================-->
    <header id="header" class="fixed-top">
      <div class="container-fluid">

        <div class="logo float-left">
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <h1 class="text-light"><a href="#header"><span>NewBiz</span></a></h1> -->
          <a href="/" class="scrollto"><img src="/assets/logo.png" alt="" class="img-fluid"></a>
        </div>

        <nav class="main-nav float-right">
          <ul>
            <% if recruiter_signed_in? %>
              <%= link_to 'Log out', destroy_recruiter_session_path, method: :delete %>
            <% elsif job_seeker_signed_in? %>
              <%= link_to 'Log out', destroy_job_seeker_session_path, method: :delete %>
            <% else %>
              <li><%= link_to "Join", welcomes_register_path %></li>
              <li><%= link_to "Recruiter Login", new_recruiter_session_path%></li>
              <li><%= link_to "Job Seeker Login", new_job_seeker_session_path%></li>
            <% end %>
          </ul>
        </nav><!-- .main-nav -->
        
      </div>
    </header><!-- #header -->

    <div class="container-fluid d-flex flex-row p-0">
        <div class="container-fluid max-height no-overflow">
          <div class ="row max-height">
            <!--SIDEBAR-->
            <% if user_signed_in? %>
              <div class="sidenav" >
              <div class='sidenav-wrapper'> <%= link_to "My profile", dashboard_profiles_show_path %></div>
              </div>   
            <% end %> 
            <!--MAIN CONTENT-->          
            <%= yield %>
          </div>
        </div>
    </div>


    <!--==========================
    Footer
  ============================-->
    <footer id="footer">
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong>Progton Technologies</strong>. All Rights Reserved
        </div>
        <div class="credits">
        </div>
      </div>
    </footer><!-- #footer -->

    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

<script type="text/javascript">
    function myClick() {
      //   var text=$('#showbutton').attr('aria-expanded');
      //   if(text == "true"){
      //     $('#showbutton').innerText='Show less';
      //   } else{
      //      $('#showbutton').innerText='Show more';
      //  }
      // });
      
      if(document.getElementById('showbutton').attributes["aria-expanded"]){
        document.getElementById('showbutton').innerText="Show Less"
      }else{
        document.getElementById('showbutton').innerText="Show More"
      }
    }
</script>
  </body>

</html>

app/views/welcomes/register.html.erb
<div class="container d-flex justify-content-center align-items-center" style= "height:100vh" >
	<div class = "d-flex">
		<div class='simple-card'>
			<a href="<%= new_recruiter_registration_path %>">
				<%= image_tag("/assets/research.svg", class: "rounded card-custom img-fluid") %>
				<p>Recruiter</p>
      </a>
		</div>
	  <div class='simple-card'>
      <a href="<%=  new_job_seeker_registration_path %>">
				<%= image_tag("/assets/thinking.svg", class: "rounded card-custom img-fluid") %>
				<p>Job Seeker</p>
      </a>
	  </div>
	</div>
</div>